#! /bin/sh
####################################################################
function build_tools()
{
sed -e "s:^F77*=\"gfortran\":F77=\"$1\":"  \
-e "s:^CC*=\"gcc\":CC=\"$2\":"  maketools >maketools.buildbot
chmod +x maketools.buildbot


maketools.buildbot clean            $HERE_T

cd prenek
sed -e "s:1 000 000:10 000:" basics.inc>t.t
mv t.t basics.inc

cd ../
maketools.buildbot all     $HERE_T  | tee $3
}
####################################################################
function moveLog()
{
#Find all log files and error files and put into directory
mv ../../examples/*/*log.*     $1
mv ../../examples/*/*.err*     $1
}
####################################################################
function submake()
{
sed -e "s:^F77*=\"mpif77\":F77=\"$1\":"  \
-e "s:^CC*=\"mpicc\":CC=\"$2\":"  \
-e "s:\#IFMPI*=:IFMPI=:"  makenek >makenek.bb
}
####################################################################
#Create Directories 
mkdir tools
mkdir mpiLog;  mkdir mpi2Log
mkdir gnuLog;  mkdir gnu2Log
mkdir intLog;  mkdir int2Log
mkdir pgiLog;  mkdir pgi2Log

#Create variable to store source path for tools
cd tools
HERE_T=`pwd`
cd ../../

#Prep maketools file:
sed -i "s:BIGMEM=\"true\":BIGMEM=\"false\":" ./trunk/tools/maketools

#2d_eig test tweak
sed -i "s:makenek:makenek.bb:g" ./examples/2d_eigtest/doall
sed -i "s:makenek:makenek.bb:g" ./examples/2d_eigtest/doit

#Tweak SIZE files 
sed -i "s:lx2=.*:lx2=lx1):"  */*/SIZE
sed -i "s:lx2=.*:lx2=lx1):"  examples/cone/*/SIZE
sed -i "s:ly2=.*:ly2=ly1):"  */*/SIZE
sed -i "s:ly2=.*:ly2=ly1):"  examples/cone/*/SIZE
sed -i "s:lz2=.*:lz2=lz1):"  */*/SIZE
sed -i "s:lz2=.*:lz2=lz1):"  examples/cone/*/SIZE

sed -i "s:(lx1=4,ly1=lx1,lz1=lx1,lelt=1500,lelv=lelt):(lx1=4,ly1=lx1,lz1=lx1,lelt=6000,lelv=lelt):" examples/moab/SIZE
sed -i "s:(lx1=10,ly1=lx1,lz1=1,lelt=80,lelv=lelt):(lx1=8,ly1=lx1,lz1=1,lelt=80,lelv=lelt):" examples/vortex2/SIZE
sed -i "s:(lxd=15,lyd=lxd,lzd=1):(lxd=12,lyd=lxd,lzd=1):" examples/vortex2/SIZE

#Tweak .rea files 
cd ./examples/eddy/
sed "s/^.*DIVERGENCE$/  0.10000E-08/" eddy_uv.rea > n.rea      
mv n.rea eddy_uv.rea
cd ../lowMach_test
sed "s/^.*IFNAV.*$/  T T IFNAV & IFADVC/" lowMach_test.rea > n.rea
mv n.rea lowMach_test.rea
cd ../moab
sed -i "s/^.*p15.*$/ 100&/" pipe.rea
cd ../vortex2
sed -i "s/^.*p11.*$/ 8000&/" v2d.rea
cd ../../tests/test0001/
sed "s/^.*DIVERGENCE$/  0.10000E-08/" test0001.rea > n.rea      
mv n.rea test0001.rea

#makenek.bb
cd ../../
cp ./trunk/nek/makenek ./trunk/nek/makenek.bb
chmod +x ./trunk/nek/makenek.bb

##############################################################
##############################################################
#Test all Compilers for Pn-Pn Case
#Builds tools with all compilers
##############################################################
##############################################################
#Build tools with pgi compiler
cd ./trunk/tools/
build_tools pgf77 pgcc ../../tests/pgitools.out

####Test MPI Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
cp ../../trunk/nek/makenek.bb .
sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"-pgcpplibs\"/" \
    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-par-mpich-pgi\":" makenek.bb>t.t
mv t.t makenek.bb
chmod +x makenek.bb
cd ../moab_conjht
cp ../../trunk/nek/makenek.bb .
sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"-pgcpplibs\"/" \
    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-par-mpich-pgi\":" makenek.bb>t.t
mv t.t makenek.bb
chmod +x makenek.bb

cd ../../trunk/nek

rm -rf ../../examples/*/*.map
../../tests/ExTestmpi

moveLog ../../tests/mpiLog
mv ../../tests/test0001/*log.*  ../../tests/mpiLog


####Test PG Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"pgf77\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"pgcc\":"     makenek.bb
sed -i "s:\#IFMPI*=:IFMPI=:"          makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-pgi\":" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"pgf77\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"pgcc\":"     makenek.bb
sed -i "s:\#IFMPI*=:IFMPI=:"          makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-pgi\":" makenek.bb
cd ../../trunk/nek

submake pgf77 pgcc
../../tests/ExTest
moveLog ../../tests/pgiLog

####Test GNU Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"gfortran\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"gcc\":"       makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-intel\":" makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-lmpi_cxx -lstdc++\"/" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"gfortran\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"gcc\":"       makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-intel\":" makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-lmpi_cxx -lstdc++\"/" makenek.bb
cd ../../trunk/nek

cd ../tools/
build_tools gfortran gcc ../../tests/gnutools.out

cd ../nek
submake gfortran gcc

rm -rf ../../examples/*/*.map
../../tests/ExTest

moveLog     ../../tests/gnuLog


####Test INTEL Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"ifort\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"icc\":"       makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-cxxlib\"/" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"ifort\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"icc\":"       makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-cxxlib\"/" makenek.bb
cd ../../trunk/nek

cd ../tools/
build_tools ifort icc ../../tests/inttools.out

cd ../nek
submake ifort icc

rm -rf ../../examples/*/*.map
../../tests/ExTest

moveLog     ../../tests/intLog
##############################################################
##############################################################
#Test all Compilers for Pn-Pn-2 Case
##############################################################
##############################################################
cp makenek makenek.bb

cd ../../
sed -i "s:lx2=.*:lx2=lx1-2):"  */*/SIZE
sed -i "s:lx2=.*:lx2=lx1-2):"  examples/cone/*/SIZE
sed -i "s:ly2=.*:ly2=ly1-2):"  */*/SIZE
sed -i "s:ly2=.*:ly2=ly1-2):"  examples/cone/*/SIZE

sed -i "s:lz2=.*:lz2=lz1-2):"  examples/vortex/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/mhd/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/moab/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/moab_conjht/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/peris/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/pipe/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/solid/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/turbChannel/SIZE
cd ./trunk/nek

####Test MPI Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
cp ../../trunk/nek/makenek.bb .
sed -e  "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"-pgcpplibs\"/" \
    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-par-mpich-pgi\":" makenek.bb>t.t
mv t.t makenek.bb
chmod +x makenek.bb
cd ../moab_conjht
cp ../../trunk/nek/makenek.bb .
sed -e  "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"-pgcpplibs\"/" \
    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-par-mpich-pgi\":" makenek.bb>t.t
mv t.t makenek.bb
chmod +x makenek.bb
cd ../../trunk/nek


../../tests/ExTestmpi
moveLog     ../../tests/mpi2Log
mv ../../tests/test0001/*log.* ../../tests/mpi2Log

####Test PG Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"pgf77\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"pgcc\":"     makenek.bb
sed -i "s:\#IFMPI*=:IFMPI=:"          makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-pgi\":" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"pgf77\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"pgcc\":"     makenek.bb
sed -i "s:\#IFMPI*=:IFMPI=:"          makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-pgi\":" makenek.bb
cd ../../trunk/nek

submake pgf77 pgcc
../../tests/ExTest
moveLog     ../../tests/pgi2Log

####Test GNU Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"gfortran\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"gcc\":"       makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-intel\":" makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-lmpi_cxx -lstdc++\"/" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"gfortran\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"gcc\":"       makenek.bb
sed -i "s:^MOAB_DIR.*:MOAB_DIR=\"\/home\/fathom\/libs\/MOAB-4.5pre-ser-intel\":" makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-lmpi_cxx -lstdc++\"/" makenek.bb
cd ../../trunk/nek

submake gfortran gcc
../../tests/ExTest
moveLog     ../../tests/gnu2Log

####Test INTEL Compiler####

#Tweak MOAB makenek
cd ../../examples/moab
sed -i "s:^F77*=\".*:F77=\"ifort\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"icc\":"       makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-cxxlib\"/" makenek.bb
cd ../moab_conjht
sed -i "s:^F77*=\".*:F77=\"ifort\":"  makenek.bb
sed -i "s:^CC*=\".*:CC=\"icc\":"       makenek.bb
sed -i  "0,/USR_LFLAGS.*/s//USR_LFLAGS=\"-cxxlib\"/" makenek.bb
cd ../../trunk/nek

submake ifort icc
../../tests/ExTest
moveLog     ../../tests/int2Log
##############################################################
