#!/bin/bash
# This script is designed to assist the compilation process of NEK5
#
###############################################################################
# User Settings
###############################################################################

# use MPI (default true)
IFMPI="true"

# coarse grid solver (default XXT)
IFAMG="false"

# Fortran compiler
F77="mpif77"

# C compiler
CC="mpicc"

# Optional compiler Flags
# NOTE: Flags like r8, DUNDERSCORE are detected automatically
G="-Knoieee -Ktrap=fp"

# Path of the NEK5 source 
SOURCE_ROOT="/home/$USER/nek5_svn/trunk/nek"

# Optional files to compile
#NOTE: files have to located in the same directory as makenek
#      and a makefile_usr.inc has to be provided containing the
#      compiling instructions. 
USR=""

# Optional linking libraries
USR_LIB=""


###############################################################################

# do some checks and create makefile using the settings defined above
source $SOURCE_ROOT/makenek.inc

make -f makefile 2>&1 | tee compiler.out

mkdir obj 2>/dev/null
\mv *.o ./obj 2>/dev/null
