#!/bin/bash
# This script is designed to assist the compilation process of NEK5
#
###############################################################################
# User Settings
###############################################################################

# use MPI (true or false)
IFMPI="true"

# Fortran compiler
F77="mpixlf77_r"

# C compiler
CC="mpixlc_r"

# compiler Flags
G="-qarch=450d -qtune=450" # "-Knoieee -Ktrap=fp"

# Absolute path of the NEK5 source 
SOURCE_ROOT="../../nek5_svn/trunk/core"

# linking libraries
USR_LIB=""


###############################################################################
source $SOURCE_ROOT/makenek.inc
